version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - npm
    groups:
      angular:
        patterns:
          - '@angular*'
          - '@angular-eslint/*'
          - '@schematics/*'
      nx:
        patterns:
          - 'nx'
          - '@nx/*'
      drizzle:
        patterns:
          - 'drizzle*'
          - '@neondatabase/*'
      aws:
        patterns:
          - '@aws-sdk/*'
      types:
        patterns:
          - '@types/*'

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions

  - package-ecosystem: terraform
    directory: '/terraform'
    schedule:
      interval: weekly
      day: monday
      time: '07:00'
      timezone: 'Etc/UTC'
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - terraform
