openapi: 3.0.3
info:
  title: api-gateway
  version: 0.0.1
paths:
  /v1/gateway/health:
    get:
      tags: [System]
      summary: Liveness
      responses:
        '200':
          description: OK
  /v1/gateway/ready:
    get:
      tags: [System]
      summary: Readiness
      responses:
        '200':
          description: OK
