import { MenuItemType } from '@/app/types/layout';

export const menuItems: MenuItemType[] = [
  { label: 'Insights', isTitle: true },
  {
    label: 'Dashboards',
    icon: '/assets/icons/sprite.svg#trello',
    isCollapsed: true,
    badge: { variant: 'danger', text: 'New' },
    children: [
      { label: 'Control Center', url: '/dashboards/control-center' },
      { label: 'Subscription & Billing', url: '/dashboards/subscription' },
      { label: 'Marketing & Sales', url: '/dashboards/marketing' },
      { label: 'Project Management', url: '/dashboards/project-management' },
    ],
  },
  {
    icon: '/assets/icons/sprite.svg#home',
    label: 'Blank Page',
    url: '/blank-page',
    menuKey: 'blank_page',
  },
  { label: 'Layouts', isTitle: true },
  {
    icon: '/assets/icons/sprite.svg#slash',
    isCollapsed: true,
    label: 'Authentication Pages',
    menuKey: 'authentication_pages',
    children: [
      { label: 'Login', url: '/auth/login?auth0=1' },
      { label: 'Register', url: '/auth/register?auth0=signup' },
      { label: 'Forget Password', url: '/auth/forgot-password' },
      { label: '2FA', url: '/auth/two-factor' },
      { label: 'Lock Screen', url: '/auth/lockscreen' },
    ],
  },
  {
    isCollapsed: true,
    icon: '/assets/icons/sprite.svg#alert-triangle',
    label: 'Error Pages',
    menuKey: 'error_pages',
    children: [
      { label: '404 Not Found', url: '/error/404' },
      { label: '404 Not Found 2', url: '/error/404-2' },
      { label: '500 Internal Server', url: '/error/500' },
    ],
  },
  {
    icon: '/assets/icons/sprite.svg#user',
    label: 'User Profile',
    url: '/user-profile',
    menuKey: 'user_profile',
  },
  {
    label: 'Landing',
    icon: '/assets/icons/sprite.svg#zap',
    url: '/landing',
    target: '_blank',
    menuKey: 'landing',
  },
  {
    isCollapsed: true,
    icon: '/assets/icons/sprite.svg#heart',
    label: 'Iconography',
    menuKey: 'iconography',
    children: [
      { label: 'System Icons', url: '/icons/system' },
      { label: 'FontAwesome', url: '/icons/font-awesome' },
      { label: 'Smart Admin Icons', url: '/icons/smart-admin' },
    ],
  },
  {
    icon: '/assets/icons/sprite.svg#table',
    isCollapsed: true,
    label: 'Tables',
    menuKey: 'tables',
    children: [
      { label: 'Basic Tables', url: '/tables/basic' },
      { label: 'Table Style Generator', url: '/tables/style-generator' },
    ],
  },
  {
    isCollapsed: true,
    icon: '/assets/icons/sprite.svg#database',
    label: 'TanStack Table',
    menuKey: 'tanstack_table',
    children: [
      { label: 'Data table (default)', url: '/tanstack-tables/full' },
      { label: 'Table With Search', url: '/tanstack-tables/search' },
      { label: 'Table With Pagination', url: '/tanstack-tables/pagination' },
      { label: 'Table With Checkbox', url: '/tanstack-tables/checkbox-select' },
      { label: 'Table With Delete Buttons', url: '/tanstack-tables/delete-buttons' },
      { label: 'Table With Filters', url: '/tanstack-tables/filters' },
      { label: 'Table With Sorting', url: '/tanstack-tables/sorting' },
    ],
  },
  {
    label: 'Platform',
    isCollapsed: true,
    icon: '/assets/icons/sprite.svg#cpu',
    children: [
      { label: 'Integrations', url: '/integrations' },
      { label: 'Production access', url: '/platform/production-access' },
      { label: 'Sandbox AI models', url: '/platform/sandbox-ai-models' },
      { label: 'Pricing profiles', url: '/platform/pricing-profiles' },
      { label: 'Runtime tenants', url: '/platform/runtime-tenants' },
      { label: 'API Catalog & Scopes', url: '/platform/api-catalog' },
    ],
  },
  {
    isCollapsed: true,
    icon: '/assets/icons/sprite.svg#settings',
    label: 'Settings',
    children: [
      { label: 'General', url: '/settings/general' },
      { label: 'Migrations', url: '/settings/migrations' },
      { label: 'Logging', url: '/settings/logging' },
    ],
  },
];
