import { randomUUID } from 'node:crypto';

import { getDb, meridianActionLog, type SpectraDb } from '@spectra/database';

import type { ExecutorResult } from './executor';
import type { L0Result } from './l0-gates';
import { executeAndVerify, type MeridianTask, type RunCoreDeps } from './runner';
import type { MeridianDecision } from './executor';

/**
 * Assisted phase (activation step 2): Meridian *proposes* — it runs an authoring task, verifies
 * via L0, then commits the artifact to a branch and opens a PR for a human to review/merge.
 * It NEVER commits to a default branch and NEVER auto-merges. The L0 verdict rides in the PR
 * body; an L0-failed draft is still a useful starting point a human finishes (that is the value
 * for large free-form classes like `test_author`). See docs/meridian/activation-plan.md + OQ-3.
 */

export interface ProposeArgs {
  branch: string;
  files: { path: string; content: string }[];
  commitMessage: string;
  prTitle: string;
  prBody: string;
}
export interface ProposeResult {
  branch: string;
  commitSha: string;
  prUrl: string;
}

/**
 * Pluggable git/PR backend. The real implementation (deferred until opening real PRs is
 * green-lit) should use an isolated `git worktree` + `gh pr create` against a clean base — never
 * mutating the caller's working tree or branch. Tests inject a mock; the default refuses to run.
 */
export interface GitOps {
  propose(args: ProposeArgs): Promise<ProposeResult>;
}

/** Safe default: refuses to touch git so nothing mutates the repo by accident. */
export const gitOpsNotConfigured: GitOps = {
  propose() {
    return Promise.reject(
      new Error(
        'Meridian Assisted: no GitOps configured. Inject a GitOps (real worktree+gh impl is ' +
          'gated behind explicit opt-in) — refusing to mutate the repo.',
      ),
    );
  },
};

export interface AssistedRunDeps extends RunCoreDeps {
  db?: SpectraDb;
  newRunId?: () => string;
  git?: GitOps;
  /** Timestamp for `applied_at` (injectable for deterministic tests). */
  now?: () => Date;
}

export interface AssistedRunResult {
  runId: string;
  decision: MeridianDecision;
  result: ExecutorResult;
  l0: L0Result;
  proposal: ProposeResult;
  applied: true;
}

/** `meridian/<class>/<short-run-id>` — never a default branch. */
export function meridianBranch(taskClass: string, runId: string): string {
  return `meridian/${taskClass}/${runId.replace(/[^a-zA-Z0-9-]/g, '').slice(0, 8) || 'run'}`;
}

/** Commit message with the OQ-3 provenance trailers linking the audit row. */
export function meridianCommitMessage(task: MeridianTask, runId: string, decision: MeridianDecision): string {
  return [
    `meridian(${task.taskClass}): proposed artifact (L0 ${decision})`,
    '',
    'Generated by the Meridian AI Driver (Assisted phase) for human review.',
    '',
    `Meridian-Task: ${task.taskClass}`,
    `Meridian-Run: ${runId}`,
  ].join('\n');
}

export function meridianPrBody(
  task: MeridianTask,
  result: ExecutorResult,
  l0: L0Result,
  decision: MeridianDecision,
): string {
  const gates = l0.gates.map((g) => `- [${g.ok ? 'x' : ' '}] ${g.command}`).join('\n') || '- (none)';
  return [
    `**Meridian-proposed** \`${task.taskClass}\` artifact — please review before merge.`,
    '',
    `- Executor: \`${result.model}\` (${result.tier} tier), ${result.usage.totalTokens} tokens`,
    `- L0 verification: **${l0.passed ? 'passed' : 'FAILED'}** → decision \`${decision}\``,
    '',
    '**L0 gates:**',
    gates,
    '',
    l0.passed
      ? '_L0 passed, but a human still approves this PR (Assisted phase)._'
      : '_L0 failed — this is a draft starting point; a human should finish it._',
  ].join('\n');
}

export async function runAssistedTask(
  task: MeridianTask,
  deps: AssistedRunDeps = {},
): Promise<AssistedRunResult> {
  if (!task.artifactFor) {
    throw new Error(
      `Task class "${task.taskClass}" has no artifactFor — it produces no committable file, so it ` +
        'is not Assisted-eligible (it is a check, not an authoring task).',
    );
  }
  const runId = (deps.newRunId ?? randomUUID)();
  const git = deps.git ?? gitOpsNotConfigured;

  const { result, l0, decision } = await executeAndVerify(task, deps);
  const files = task.artifactFor(result);

  const proposal = await git.propose({
    branch: meridianBranch(task.taskClass, runId),
    files,
    commitMessage: meridianCommitMessage(task, runId, decision),
    prTitle: `meridian(${task.taskClass}): proposed artifact for review`,
    prBody: meridianPrBody(task, result, l0, decision),
  });

  const db = deps.db ?? getDb();
  await db.insert(meridianActionLog).values({
    runId,
    taskClass: task.taskClass,
    phase: 'assisted',
    executorModel: result.model,
    executorTier: result.tier,
    tokensSpent: result.usage.totalTokens,
    l0Results: l0,
    decision,
    input: (task.input ?? null) as object,
    output: { text: result.text, toolUse: result.toolUse, stopReason: result.stopReason },
    branch: proposal.branch,
    prUrl: proposal.prUrl,
    commitSha: proposal.commitSha,
    appliedAt: (deps.now ?? (() => new Date()))(),
  });

  return { runId, decision, result, l0, proposal, applied: true };
}
